core/routes/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_user, login_required, logout_user, current_user
from core.models import Users
from core import db

auth = Blueprint("auth", __name__)

@auth.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        email = request.form.get("email")
        password = request.form.get("password")
        user = Users.query.filter_by(email=email).first()
        if user and user.check_password(password):
            login_user(user)
            flash("Logged in successfully!", "success")
            return redirect(url_for("web.home"))
        else:
            flash("Invalid email or password", "danger")
    return render_template("auth/login.html", user=current_user)


@auth.route("/register", methods=["GET", "POST"])
def register():
    if request.method == "POST":
        username = request.form.get("username")
        email = request.form.get("email")
        password = request.form.get("password")
        confirm_password = request.form.get("confirm_password")
        user = Users.query.filter_by(email=email).first()
        if user:
            flash("Email already exists.", "danger")
        else:
            if password != confirm_password:
                flash("Passwords do not match!", "danger")
                return redirect(url_for("auth.register"))
        
            new_user = Users(email=email, username=username)
            new_user.set_password(password)
            db.session.add(new_user)
            db.session.commit()
            flash("Account created!", "success")
            return redirect(url_for("auth.login"))
    return render_template("auth/register.html", user=current_user)


@auth.route("/logout")
@login_required
def logout():
   logout_user()
   flash("Logged out successfully!", "success")
   return redirect(url_for("web.home"))

core/routes/web.py
# core/routes/web.py
from flask import Blueprint, jsonify, request, render_template, redirect, url_for, flash
from flask_login import current_user, login_required
from sqlalchemy.exc import OperationalError
from sqlalchemy import text
from core.extensions import db
from core.models import Reviews
import requests
import os

web = Blueprint("web", __name__)
TMDB_API_KEY = os.getenv("TMDB_API_KEY")
TMDB_BASE_URL = 'https://api.themoviedb.org/3'

@web.route("/")
def home():
    url = f"{TMDB_BASE_URL}/movie/popular"
    params = {
        'api_key': TMDB_API_KEY,
        'language': 'en-US',
        'page': 1
    }
    response = requests.get(url, params=params)
    movies = response.json().get('results', [])
    
    return render_template("index.html", user=current_user, movies=movies)


@web.route("/search", methods=['GET'])
def search_movie():
    query = request.args.get('query')
    url = f"{TMDB_BASE_URL}/search/movie"
    params = {
        'api_key': TMDB_API_KEY,
        'query': query,
        'language': 'en-US',
        'page': 1
    }
    response = requests.get(url, params=params)
    movies = response.json().get('results', [])
    
    return render_template("index.html", user=current_user, movies=movies, query=query)


@web.route("/movies/<int:movie_id>")
def movie_details(movie_id):
   url = f"{TMDB_BASE_URL}/movie/{movie_id}"
   params = {
      'api_key': TMDB_API_KEY,
      'language': 'en-US'
   }
   response = requests.get(url, params=params)
   movie = response.json()

   reviews = Reviews.query.filter_by(movie_id=movie_id).all()
   return render_template("movie_details.html", reviews=reviews, movie=movie, user=current_user)


@web.route("/profile")
@login_required
def profile():
   return render_template("profile.html", user=current_user)


@web.route("/update_profile", methods=["POST"])
@login_required
def update_profile():
   current_user.username = request.form["username"]

   password = request.form["password"]
   if password:
      current_user.set_password(password)

   db.session.commit()
   flash("Profile updated successfully!", "success")
   return redirect(url_for("web.profile"))


@web.route("/your-reviews")
@login_required
def your_reviews():
   reviews = current_user.reviews
   unique_movie_ids = set(review.movie_id for review in reviews)

   movies = []
   for movie_id in unique_movie_ids:
      url = f"{TMDB_BASE_URL}/movie/{movie_id}"
      params = {
         'api_key': TMDB_API_KEY,
         'language': 'en-US'
      }
      response = requests.get(url, params=params)
      movie = response.json()
      movies.append(movie)

   return render_template("your_reviews.html", movies=movies, user=current_user)


@web.route("/reviews", methods=["POST"])
@login_required
def create_review():
   movie_id = int(request.form.get("movie_id"))
   label = request.form.get("label")
   rating = int(request.form.get("rating"))
   body = request.form.get("body")

   if not label:
       flash("Label is required!", "error")
       return redirect(url_for("web.movie_details", movie_id=movie_id))
   
   if not rating:
       flash("Rating is required!", "error")
       return redirect(url_for("web.movie_details", movie_id=movie_id))

   new_review = Reviews(label=label, rating=rating, body=body, movie_id=movie_id, user_id=current_user.id)
   db.session.add(new_review)
   db.session.commit()

   flash("Review created successfully!", "success")
   return redirect(url_for("web.movie_details", movie_id=movie_id))


@web.route("/reviews/<int:review_id>", methods=["POST"])
@login_required
def manage_review(review_id):
   action = request.form.get("action")
   review = Reviews.query.filter_by(id=review_id, user_id=current_user.id).first_or_404()

   if action == "delete":
      db.session.delete(review)
      db.session.commit()
      flash("Review deleted successfully!", "success")
   elif action == "update":
      label = request.form.get("label")
      rating = int(request.form.get("rating"))
      body = request.form.get("body")

      if not label:
         flash("Label is required!", "error")
         return redirect(url_for("web.movie_details", movie_id=review.movie_id))

      if not rating:
         flash("Rating is required!", "error")
         return redirect(url_for("web.movie_details", movie_id=review.movie_id))

      review.label = label
      review.rating = rating
      review.body = body
      db.session.commit()
      flash("Review updated successfully!", "success")
   else:
      flash("Invalid action.", "error")

   return redirect(url_for("web.movie_details", movie_id=review.movie_id))


@web.route("/ping")
def ping():
    """Check if the web app and DB are awake."""
    try:
        # Lightweight query to wake up Postgres
        db.session.execute(text("SELECT 1"))
        return jsonify({"status": "ok", "db": "ready"})
    except OperationalError:
        return jsonify({"status": "error", "db": "sleeping"}), 503

core/templates/partials/_flashes.html
<!-- _flashes.html -->
{% with messages=get_flashed_messages(with_categories=true) %}
 {% if messages %}
   <div class="container">
     <div class="row justify-content-center">
       <div class="col-md-12">
         {% for category, message in messages %}
           <div class="alert alert-{{ category }} alert-dismissible fade show"
             role="alert">
             {{ message }}
             <button type="button"
               class="btn-close"
               data-bs-dismiss="alert"
               aria-label="Close">
             </button>
           </div>
         {% endfor %}
       </div>
     </div>
   </div>
 {% endif %}
{% endwith %}

core/templates/partials/_navbar.html
<nav class="navbar navbar-expand-lg bg-transparent py-1" data-bs-theme="dark">
 <div class="container">
   <a class="navbar-brand fs-3 fw-semibold" href="{{ url_for('web.home') }}"><i class="bi bi-camera-reels me-1 text-primary"></i>Groovy Movies</a>
   <button class="navbar-toggler"
     type="button"
     data-bs-toggle="collapse"
     data-bs-target="#navbarContent"
     aria-controls="navbarContent"
     aria-expanded="false"
     aria-label="Toggle navigation">
     <span class="navbar-toggler-icon"></span>
   </button>
   <div class="collapse navbar-collapse" id="navbarContent">
     <ul class="navbar-nav ms-auto">
       {% if user.is_authenticated %}
        <li class="nav-item dropdown">
          <a class="nav-link d-flex align-items-center fw-semibold" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
            {{ user.username }}
            <i class="bi bi-person-circle fs-2 ms-1"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-end">
            <a class="dropdown-item" href="{{ url_for('web.profile') }}">Profile</a>
            <a class="dropdown-item" href="{{ url_for('web.your_reviews') }}">Your Reviews</a>
            <a class="dropdown-item text-danger" href="{{ url_for('auth.logout') }}">Logout</a>
          </div>
        </li>
       {% else %}
         <li class="nav-item">
           <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
         </li>
         <li class="nav-item">
           <a class="nav-link" href="{{ url_for('auth.register') }}">Signup</a>
         </li>
       {% endif %}
     </ul>
   </div>
 </div>
</nav>